runtime: python27
api_version: 1
threadsafe: true
handlers:
- url: /
  static_files: dist/managed-word-cards/index.html
  upload: dist/managed-word-cards/index.html
- url: /
  static_dir: dist/managed-word-cards

skip_files:
  - e2e/
  - node_modules/
  - src/
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE
