runtime: python38
instance_class: F1

handlers:
  - url: /
    static_files: dist/managed-word-cards/index.html
    upload: dist/managed-word-cards/index.html
  - url: /
    static_dir: dist/managed-word-cards

